version: "3.9"

services:
  postgres:
     image: postgres:15.3-alpine
     container_name: postgress-container_name
     restart: unless-stopped
     environment:
        POSTGRES_USER: ${POSTGRES_USER:-dev-user}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lovkush}
        POSTGRES_DB: ${POSTGRES_DB:-dev-db}

     ports:
       - "5432:5432" 

     volumes:
       - postgres_data:/var/lib/postgresql/data
       - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

     networks:
       - jausathe   

     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-dev-user}"]   
       interval: 10s
       timeout: 5s
       retries: 5
       start_period: 30s

  redis:
    image: redis:7.2-alpine
    container_name: redis-container_name
    restart: unless-stopped

    ports:
      - "6279:6379"

    volumes:
      - redis_data:/data 

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile       
      target: builder

    container_name: backend-container_name
    restart: unless-stopped
    ports:
      - "8000:8000"

    environment:
      - NODE_ENV=development
      - PORT=8000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-dev-user}:${POSTGRES_PASSWORD:-lovkush}@postgres:5432/${POSTGRES_DB:-dev-db}
      - REDIS_URL=redis://redis:6379 

    volumes:
      - ./backend/src:/app/src  
      - /app/node_modules


    networks:
      - jausathe  

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile           
      target: builder
    container_name: frontend-container
    restart: unless-stopped
    ports:
      - "5173:5173"

    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules  

    depends_on:
        - backend

    networks:
      - jausathe

volumes:
  postgres_data:
    driver: local

  redis_data:
    driver: local


networks:
  jausathe:
     driver: bridge    

            


