apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: jausathe-namespace


type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: bG92a3VzaA==  
  POSTGRES_DB: amF1c2F0aGU=
