apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  metadata: jausathe

spec: 
  type: clusterIp
  selector:
    app: frontend 
  ports:
    - name: fronted-service
      port: 5473
      targetPort: 5473
      protocol: TCP
      
