/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplashIndexRouteImport } from './routes/Splash/index'
import { Route as BoardingPage3IndexRouteImport } from './routes/boarding/page3/index'
import { Route as BoardingPage2IndexRouteImport } from './routes/boarding/page2/index'
import { Route as BoardingPage1IndexRouteImport } from './routes/boarding/page1/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/Signup/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashIndexRoute = SplashIndexRouteImport.update({
  id: '/Splash/',
  path: '/Splash/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingPage3IndexRoute = BoardingPage3IndexRouteImport.update({
  id: '/boarding/page3/',
  path: '/boarding/page3/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingPage2IndexRoute = BoardingPage2IndexRouteImport.update({
  id: '/boarding/page2/',
  path: '/boarding/page2/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingPage1IndexRoute = BoardingPage1IndexRouteImport.update({
  id: '/boarding/page1/',
  path: '/boarding/page1/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/Signup/',
  path: '/auth/Signup/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Splash/': typeof SplashIndexRoute
  '/auth/Signup/': typeof AuthSignupIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/boarding/page1/': typeof BoardingPage1IndexRoute
  '/boarding/page2/': typeof BoardingPage2IndexRoute
  '/boarding/page3/': typeof BoardingPage3IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Splash': typeof SplashIndexRoute
  '/auth/Signup': typeof AuthSignupIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/boarding/page1': typeof BoardingPage1IndexRoute
  '/boarding/page2': typeof BoardingPage2IndexRoute
  '/boarding/page3': typeof BoardingPage3IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Splash/': typeof SplashIndexRoute
  '/auth/Signup/': typeof AuthSignupIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/boarding/page1/': typeof BoardingPage1IndexRoute
  '/boarding/page2/': typeof BoardingPage2IndexRoute
  '/boarding/page3/': typeof BoardingPage3IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Splash/'
    | '/auth/Signup/'
    | '/auth/login/'
    | '/boarding/page1/'
    | '/boarding/page2/'
    | '/boarding/page3/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Splash'
    | '/auth/Signup'
    | '/auth/login'
    | '/boarding/page1'
    | '/boarding/page2'
    | '/boarding/page3'
  id:
    | '__root__'
    | '/'
    | '/Splash/'
    | '/auth/Signup/'
    | '/auth/login/'
    | '/boarding/page1/'
    | '/boarding/page2/'
    | '/boarding/page3/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplashIndexRoute: typeof SplashIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  BoardingPage1IndexRoute: typeof BoardingPage1IndexRoute
  BoardingPage2IndexRoute: typeof BoardingPage2IndexRoute
  BoardingPage3IndexRoute: typeof BoardingPage3IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Splash/': {
      id: '/Splash/'
      path: '/Splash'
      fullPath: '/Splash/'
      preLoaderRoute: typeof SplashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding/page3/': {
      id: '/boarding/page3/'
      path: '/boarding/page3'
      fullPath: '/boarding/page3/'
      preLoaderRoute: typeof BoardingPage3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding/page2/': {
      id: '/boarding/page2/'
      path: '/boarding/page2'
      fullPath: '/boarding/page2/'
      preLoaderRoute: typeof BoardingPage2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding/page1/': {
      id: '/boarding/page1/'
      path: '/boarding/page1'
      fullPath: '/boarding/page1/'
      preLoaderRoute: typeof BoardingPage1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/Signup/': {
      id: '/auth/Signup/'
      path: '/auth/Signup'
      fullPath: '/auth/Signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplashIndexRoute: SplashIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  BoardingPage1IndexRoute: BoardingPage1IndexRoute,
  BoardingPage2IndexRoute: BoardingPage2IndexRoute,
  BoardingPage3IndexRoute: BoardingPage3IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
