/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DriverDashboardRouteImport } from './routes/DriverDashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplashIndexRouteImport } from './routes/Splash/index'
import { Route as ProfileIndexRouteImport } from './routes/Profile/index'
import { Route as DriverProfileRouteImport } from './routes/Driver/profile'
import { Route as BoardingPage3IndexRouteImport } from './routes/boarding/page3/index'
import { Route as BoardingPage2IndexRouteImport } from './routes/boarding/page2/index'
import { Route as BoardingPage1IndexRouteImport } from './routes/boarding/page1/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/Signup/index'
import { Route as DriverTripsIndexRouteImport } from './routes/Driver/trips/index'
import { Route as DriverAuthIndexRouteImport } from './routes/Driver/auth/index'
import { Route as DriverEarningsIndexRouteImport } from './routes/Driver/Earnings/index'
import { Route as BookPaymentIndexRouteImport } from './routes/Book/Payment/index'
import { Route as BookMyRidesIndexRouteImport } from './routes/Book/MyRides/index'
import { Route as BookBookRidesIndexRouteImport } from './routes/Book/BookRides/index'

const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/DriverDashboard',
  path: '/DriverDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashIndexRoute = SplashIndexRouteImport.update({
  id: '/Splash/',
  path: '/Splash/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/Profile/',
  path: '/Profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/Driver/profile',
  path: '/Driver/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingPage3IndexRoute = BoardingPage3IndexRouteImport.update({
  id: '/boarding/page3/',
  path: '/boarding/page3/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingPage2IndexRoute = BoardingPage2IndexRouteImport.update({
  id: '/boarding/page2/',
  path: '/boarding/page2/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingPage1IndexRoute = BoardingPage1IndexRouteImport.update({
  id: '/boarding/page1/',
  path: '/boarding/page1/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/Signup/',
  path: '/auth/Signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTripsIndexRoute = DriverTripsIndexRouteImport.update({
  id: '/Driver/trips/',
  path: '/Driver/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverAuthIndexRoute = DriverAuthIndexRouteImport.update({
  id: '/Driver/auth/',
  path: '/Driver/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverEarningsIndexRoute = DriverEarningsIndexRouteImport.update({
  id: '/Driver/Earnings/',
  path: '/Driver/Earnings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookPaymentIndexRoute = BookPaymentIndexRouteImport.update({
  id: '/Book/Payment/',
  path: '/Book/Payment/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookMyRidesIndexRoute = BookMyRidesIndexRouteImport.update({
  id: '/Book/MyRides/',
  path: '/Book/MyRides/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookRidesIndexRoute = BookBookRidesIndexRouteImport.update({
  id: '/Book/BookRides/',
  path: '/Book/BookRides/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/DriverDashboard': typeof DriverDashboardRoute
  '/Driver/profile': typeof DriverProfileRoute
  '/Profile/': typeof ProfileIndexRoute
  '/Splash/': typeof SplashIndexRoute
  '/Book/BookRides/': typeof BookBookRidesIndexRoute
  '/Book/MyRides/': typeof BookMyRidesIndexRoute
  '/Book/Payment/': typeof BookPaymentIndexRoute
  '/Driver/Earnings/': typeof DriverEarningsIndexRoute
  '/Driver/auth/': typeof DriverAuthIndexRoute
  '/Driver/trips/': typeof DriverTripsIndexRoute
  '/auth/Signup/': typeof AuthSignupIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/boarding/page1/': typeof BoardingPage1IndexRoute
  '/boarding/page2/': typeof BoardingPage2IndexRoute
  '/boarding/page3/': typeof BoardingPage3IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/DriverDashboard': typeof DriverDashboardRoute
  '/Driver/profile': typeof DriverProfileRoute
  '/Profile': typeof ProfileIndexRoute
  '/Splash': typeof SplashIndexRoute
  '/Book/BookRides': typeof BookBookRidesIndexRoute
  '/Book/MyRides': typeof BookMyRidesIndexRoute
  '/Book/Payment': typeof BookPaymentIndexRoute
  '/Driver/Earnings': typeof DriverEarningsIndexRoute
  '/Driver/auth': typeof DriverAuthIndexRoute
  '/Driver/trips': typeof DriverTripsIndexRoute
  '/auth/Signup': typeof AuthSignupIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/boarding/page1': typeof BoardingPage1IndexRoute
  '/boarding/page2': typeof BoardingPage2IndexRoute
  '/boarding/page3': typeof BoardingPage3IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/DriverDashboard': typeof DriverDashboardRoute
  '/Driver/profile': typeof DriverProfileRoute
  '/Profile/': typeof ProfileIndexRoute
  '/Splash/': typeof SplashIndexRoute
  '/Book/BookRides/': typeof BookBookRidesIndexRoute
  '/Book/MyRides/': typeof BookMyRidesIndexRoute
  '/Book/Payment/': typeof BookPaymentIndexRoute
  '/Driver/Earnings/': typeof DriverEarningsIndexRoute
  '/Driver/auth/': typeof DriverAuthIndexRoute
  '/Driver/trips/': typeof DriverTripsIndexRoute
  '/auth/Signup/': typeof AuthSignupIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/boarding/page1/': typeof BoardingPage1IndexRoute
  '/boarding/page2/': typeof BoardingPage2IndexRoute
  '/boarding/page3/': typeof BoardingPage3IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/DriverDashboard'
    | '/Driver/profile'
    | '/Profile/'
    | '/Splash/'
    | '/Book/BookRides/'
    | '/Book/MyRides/'
    | '/Book/Payment/'
    | '/Driver/Earnings/'
    | '/Driver/auth/'
    | '/Driver/trips/'
    | '/auth/Signup/'
    | '/auth/login/'
    | '/boarding/page1/'
    | '/boarding/page2/'
    | '/boarding/page3/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/DriverDashboard'
    | '/Driver/profile'
    | '/Profile'
    | '/Splash'
    | '/Book/BookRides'
    | '/Book/MyRides'
    | '/Book/Payment'
    | '/Driver/Earnings'
    | '/Driver/auth'
    | '/Driver/trips'
    | '/auth/Signup'
    | '/auth/login'
    | '/boarding/page1'
    | '/boarding/page2'
    | '/boarding/page3'
  id:
    | '__root__'
    | '/'
    | '/DriverDashboard'
    | '/Driver/profile'
    | '/Profile/'
    | '/Splash/'
    | '/Book/BookRides/'
    | '/Book/MyRides/'
    | '/Book/Payment/'
    | '/Driver/Earnings/'
    | '/Driver/auth/'
    | '/Driver/trips/'
    | '/auth/Signup/'
    | '/auth/login/'
    | '/boarding/page1/'
    | '/boarding/page2/'
    | '/boarding/page3/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriverDashboardRoute: typeof DriverDashboardRoute
  DriverProfileRoute: typeof DriverProfileRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SplashIndexRoute: typeof SplashIndexRoute
  BookBookRidesIndexRoute: typeof BookBookRidesIndexRoute
  BookMyRidesIndexRoute: typeof BookMyRidesIndexRoute
  BookPaymentIndexRoute: typeof BookPaymentIndexRoute
  DriverEarningsIndexRoute: typeof DriverEarningsIndexRoute
  DriverAuthIndexRoute: typeof DriverAuthIndexRoute
  DriverTripsIndexRoute: typeof DriverTripsIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  BoardingPage1IndexRoute: typeof BoardingPage1IndexRoute
  BoardingPage2IndexRoute: typeof BoardingPage2IndexRoute
  BoardingPage3IndexRoute: typeof BoardingPage3IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/DriverDashboard': {
      id: '/DriverDashboard'
      path: '/DriverDashboard'
      fullPath: '/DriverDashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Splash/': {
      id: '/Splash/'
      path: '/Splash'
      fullPath: '/Splash/'
      preLoaderRoute: typeof SplashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Profile/': {
      id: '/Profile/'
      path: '/Profile'
      fullPath: '/Profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Driver/profile': {
      id: '/Driver/profile'
      path: '/Driver/profile'
      fullPath: '/Driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding/page3/': {
      id: '/boarding/page3/'
      path: '/boarding/page3'
      fullPath: '/boarding/page3/'
      preLoaderRoute: typeof BoardingPage3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding/page2/': {
      id: '/boarding/page2/'
      path: '/boarding/page2'
      fullPath: '/boarding/page2/'
      preLoaderRoute: typeof BoardingPage2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding/page1/': {
      id: '/boarding/page1/'
      path: '/boarding/page1'
      fullPath: '/boarding/page1/'
      preLoaderRoute: typeof BoardingPage1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/Signup/': {
      id: '/auth/Signup/'
      path: '/auth/Signup'
      fullPath: '/auth/Signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Driver/trips/': {
      id: '/Driver/trips/'
      path: '/Driver/trips'
      fullPath: '/Driver/trips/'
      preLoaderRoute: typeof DriverTripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Driver/auth/': {
      id: '/Driver/auth/'
      path: '/Driver/auth'
      fullPath: '/Driver/auth/'
      preLoaderRoute: typeof DriverAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Driver/Earnings/': {
      id: '/Driver/Earnings/'
      path: '/Driver/Earnings'
      fullPath: '/Driver/Earnings/'
      preLoaderRoute: typeof DriverEarningsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Book/Payment/': {
      id: '/Book/Payment/'
      path: '/Book/Payment'
      fullPath: '/Book/Payment/'
      preLoaderRoute: typeof BookPaymentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Book/MyRides/': {
      id: '/Book/MyRides/'
      path: '/Book/MyRides'
      fullPath: '/Book/MyRides/'
      preLoaderRoute: typeof BookMyRidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Book/BookRides/': {
      id: '/Book/BookRides/'
      path: '/Book/BookRides'
      fullPath: '/Book/BookRides/'
      preLoaderRoute: typeof BookBookRidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriverDashboardRoute: DriverDashboardRoute,
  DriverProfileRoute: DriverProfileRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SplashIndexRoute: SplashIndexRoute,
  BookBookRidesIndexRoute: BookBookRidesIndexRoute,
  BookMyRidesIndexRoute: BookMyRidesIndexRoute,
  BookPaymentIndexRoute: BookPaymentIndexRoute,
  DriverEarningsIndexRoute: DriverEarningsIndexRoute,
  DriverAuthIndexRoute: DriverAuthIndexRoute,
  DriverTripsIndexRoute: DriverTripsIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  BoardingPage1IndexRoute: BoardingPage1IndexRoute,
  BoardingPage2IndexRoute: BoardingPage2IndexRoute,
  BoardingPage3IndexRoute: BoardingPage3IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
